Fix an issue when adding a node then removing a node caused "Contains…
danielkylewood/concurrent-linked-list pull request #3
Opened 2019-09-30 19:20 UTC by jmfallecker

…" function for that node to thrown a NullReferenceException instead of returning "false"

2019-09-30 19:36 UTC, jmfallecker commented
Well, the first commit should definitely go in.

I was going only off of current code functionality (what looks like should be that if a node with state REM is attempted to be removed, that it returns false.

This seems to break the Integration test.

Hope you're well, and nice implementation of this!

-Joe

2019-10-17 23:16 UTC, danielkylewood commented
Sorry dude, just returned from vacation and saw this. Will have a look tomorrow.

2019-10-18 22:08 UTC, danielkylewood requested changes

2019-10-18 22:08 UTC, danielkylewood commented on src/ConcurrentLinkedList/ConcurrentLinkedList.cs
> +                else if (state == NodeState.REM)
I don't think moving this check here is right. It solves the immediate problem, but stops threads finding the nodes they are looking to remove (hence the failing tests). I think solution is to change the node value check to also check for null, as you did in first commit. 

So `else if (!current.Value.Equals(value))` => `else if (current.Value != null && !current.Value.Equals(value))` and move this check back to where it was. Your added test passes with this as well.

2019-10-18 22:11 UTC, danielkylewood commented
I think with the one suggested change then all works fine. Your assumptions on expected behaviour are right, the exceptions were definitely an oversight on my part so thanks!

2019-11-23 19:34 UTC, danielkylewood commented
Closing due to inactivity

2019-11-23 19:34 UTC, closed without merging